language: python
python:
  - 2.7
  - 3.6
  - pypy
  - pypy3
env:
  - DJANGO=1.8.18
  - DJANGO=1.9.13
  - DJANGO=1.10.8
  - DJANGO=1.11.10
  - DJANGO=2.0.2
  - DJANGO=2.1
before_install:
  - export DJANGO_SETTINGS_MODULE=suit.tests.settings
install:
  - pip --no-cache-dir install --upgrade pip
  - pip --no-cache-dir install -q Django==$DJANGO
  - pip install .
script:
  - python manage.py test suit
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 2.7
      env: DJANGO=2.0.2
    - python: pypy
      env: DJANGO=2.0.2
    - python: 2.7
      env: DJANGO=2.1
    - python: pypy
      env: DJANGO=2.1
